### ISSUE TITLE
Missing twitter timeline features

### ISSUE THREAD

**Issue by nerik** [Vizzuality/TRASE-frontend#342]
- [ ] link to tweet
- [ ] clickable handle
- [ ] and @ to twitter handle
- [ ] clickable links

**Comment by nerik** [comment]
Note: those features were implemented in the node API, you can reuse the code there maybe

**Comment by nerik** [comment]
Also let me know if I can remove this plz: https://github.com/Vizzuality/TRASE-social

**Comment by tiagojsag** [comment]
yes, let's delete that repo. we should add those elements to the rail content api
