### ISSUE TITLE
Names overlap in Line chart

### ISSUE THREAD

**Issue by sorodrigo** [Vizzuality/TRASE-frontend#377]
When the values are similar the labels of the lines are overlapping.

**Comment by nerik** [comment]
See @juancarlosalonso suggestion: https://github.com/tinker10/D3-Labeler

**Comment by nerik** [comment]
If you need help please refer to Monte Carlo sweeps for simulated annealing:
![screen shot 2017-05-10 at 12 47 18](https://cloud.githubusercontent.com/assets/1583415/25895121/e052b4da-357e-11e7-9133-632ccb11e202.png)
