### ISSUE TITLE
Profile graph tweaks

### ISSUE THREAD

**Issue by juancarlosalonso** [Vizzuality/TRASE-frontend#385]
- [x] Y axis labels get cut
- [x] X axis should just read "2015  -  2016"
- [x] Line labels should be capitalized, not everything uppercase
- [x] #377
- [x] put legend on top of both graph and map
- [x] line colors should match choro colors

**Comment by nerik** [comment]
![screen shot 2017-06-07 at 11 58 05](https://user-images.githubusercontent.com/1583415/26872945-93a2c4ee-4b78-11e7-9b6b-3b6c33dc7e36.png)
