### ISSUE TITLE
Layer Selector Tweaks

### ISSUE THREAD

**Issue by juancarlosalonso** [Vizzuality/TRASE-frontend#388]
- [ ] "TERRITORIAL GOVERNANCE" should be "TERRITORIAL GOVERNANCE INDICATORS" for consistency
- [ ] Info icon default colour should be the light grey, like in disabled state
- [ ] Disabled layers should not show hand cursor, please change to "not-allowed" like in the map

**Comment by tiagojsag** [comment]
https://github.com/Vizzuality/trase/issues/118
