### ISSUE TITLE
Use ISO2 codes for countries 

### ISSUE THREAD

**Issue by nerik** [Vizzuality/TRASE-frontend#414]
When https://github.com/Vizzuality/trase-api/issues/19 is ready, we should use iso2 codes to avoid false negatives when matching actor top countries against map polygons.
A new topoJson file should also be regenerated with the iso codes (don't forget to remove Hawaii and other polygons in the middle of the pacific)

**Comment by tiagojsag** [comment]
@nerik still relevant?

**Comment by nerik** [comment]
Yes, I just opened a PR, to use in the FE the changes made in the backend.

**Comment by nerik** [comment]
https://github.com/Vizzuality/trase/pull/130
