### ISSUE TITLE
Place profile: display soy land value in Ha

### ISSUE THREAD

**Issue by agnessa** [Vizzuality/TRASE-frontend#470]
For the "SOY LAND" header stat, instead of the `soy_farmland` attribute which is a % please use `soy_area` which is in Ha (it's the same value as "land occupied by soy" in the summary text). Unfortunately, the unit is hardcoded, for some reason that is the way we did for all header stats :( So this requires a front end change. It's a much longer number as well.

Related commit: https://github.com/Vizzuality/trase-api/commit/789abb15a25976dac85e2366400499d8f3a94430

Request comes from: https://github.com/Vizzuality/trase-api/commit/789abb15a25976dac85e2366400499d8f3a94430

**Comment by nerik** [comment]
Before:
![screen shot 2017-09-19 at 12 29 40](https://user-images.githubusercontent.com/1583415/30588514-4614ae52-9d37-11e7-8ed4-076d18c5b3dc.png)

After:
![screen shot 2017-09-19 at 12 37 02](https://user-images.githubusercontent.com/1583415/30588521-4945aa86-9d37-11e7-81ce-6afc2245601b.png)

Looks good to you?

**Comment by nerik** [comment]
It looks like this value is often set to "NaN" in the API response, for instance:
http://staging.trase.earth/api/v2/get_place_node_attributes?&node_id=13999

**Comment by nerik** [comment]
(also in the summary)

**Comment by agnessa** [comment]
Would you rather it was 0 when not available?

**Comment by nerik** [comment]
Usually in that kind of situation `null` or the absence of the value in the object would seem better.

But it needs to be handled on the API side in the text blurb anyways:
![screen shot 2017-09-19 at 13 15 36](https://user-images.githubusercontent.com/1583415/30589919-b44bbdc0-9d3c-11e7-8647-e36804e4e532.png)

**Comment by tiagojsag** [comment]
@agnessa @nerik I think there's nothing left to do here, but can one of you confirm please?

thanks

**Comment by agnessa** [comment]
I'm not sure empty values are handled in the blurb. In other words the original issue is resolved, but the NaN issue probably not.

**Comment by tiagojsag** [comment]
good enough IMO
