### ISSUE TITLE
Question: can I remove total_soy_2015 from API response?

### ISSUE THREAD

**Issue by agnessa** [Vizzuality/TRASE-frontend#475]
The actor profile API returns the value of total volume of soy traded as in this mock:

https://github.com/Vizzuality/TRASE-frontend/blob/de973204ea84f3c8365fe04dec19aba4db249aa9/public/mocks/v1_get_actor_node_attributes.json#L408

Is this used anywhere? It would be easiest to remove it from the backend because it is calculated using a deprecated calculation method (the SOY_ quant); otherwise, if it is needed, it has to be calculated differently, and I'd propose a change in this attribute's name so that it is more generic and does not include the year in the name, e.g. `total_volume`.

**Comment by tiagojsag** [comment]
I see no usage of this in the frontend code, so I think it's a "yes, can be removed"
